#############################################################################
# Generated by PAGE version 4.3.1
# in conjunction with Tcl version 8.6
#    Oct 25, 2014 10:16:24 AM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top47
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 200x200+52+52; update
    wm maxsize $top 1276 773
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page"
    bindtags $top "$top Page all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top47 {base} {
    if {$base == ""} {
        set base .top47
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 516x355+344+122; update
    wm maxsize $top 1276 773
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Calibration Mode"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    label $top.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 10 
    vTcl:DefineAlias "$top.lab53" "l10" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 04 
    vTcl:DefineAlias "$top.cpd55" "l4" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 03 
    vTcl:DefineAlias "$top.cpd56" "l3" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 09 
    vTcl:DefineAlias "$top.cpd57" "l9" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 08 
    vTcl:DefineAlias "$top.cpd58" "l8" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 07 
    vTcl:DefineAlias "$top.cpd59" "l7" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 06 
    vTcl:DefineAlias "$top.cpd60" "l6" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 05 
    vTcl:DefineAlias "$top.cpd61" "l5" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 01 
    vTcl:DefineAlias "$top.cpd62" "l1" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd75 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 11 
    vTcl:DefineAlias "$top.cpd75" "l11" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd76 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 12 
    vTcl:DefineAlias "$top.cpd76" "l12" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd77 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 20 
    vTcl:DefineAlias "$top.cpd77" "l20" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd78 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 19 
    vTcl:DefineAlias "$top.cpd78" "l19" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd79 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 18 
    vTcl:DefineAlias "$top.cpd79" "l18" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd80 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 17 
    vTcl:DefineAlias "$top.cpd80" "l17" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd81 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 16 
    vTcl:DefineAlias "$top.cpd81" "l16" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd82 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 15 
    vTcl:DefineAlias "$top.cpd82" "l15" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd83 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 14 
    vTcl:DefineAlias "$top.cpd83" "l14" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd84 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 13 
    vTcl:DefineAlias "$top.cpd84" "l13" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd85 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 30 
    vTcl:DefineAlias "$top.cpd85" "l30" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd86 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 29 
    vTcl:DefineAlias "$top.cpd86" "l29" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd87 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 28 
    vTcl:DefineAlias "$top.cpd87" "l28" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd88 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 27 
    vTcl:DefineAlias "$top.cpd88" "l27" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd89 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 26 
    vTcl:DefineAlias "$top.cpd89" "l26" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd90 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 25 
    vTcl:DefineAlias "$top.cpd90" "l25" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd91 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 24 
    vTcl:DefineAlias "$top.cpd91" "l24" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd92 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 23 
    vTcl:DefineAlias "$top.cpd92" "l23" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd93 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 22 
    vTcl:DefineAlias "$top.cpd93" "l22" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd94 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 21 
    vTcl:DefineAlias "$top.cpd94" "l21" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd95 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 50 
    vTcl:DefineAlias "$top.cpd95" "l50" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd96 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 49 
    vTcl:DefineAlias "$top.cpd96" "l49" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd97 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 48 
    vTcl:DefineAlias "$top.cpd97" "l48" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd98 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 47 
    vTcl:DefineAlias "$top.cpd98" "l47" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd99 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 46 
    vTcl:DefineAlias "$top.cpd99" "l46" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd100 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 45 
    vTcl:DefineAlias "$top.cpd100" "l45" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd101 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 44 
    vTcl:DefineAlias "$top.cpd101" "l44" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd102 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 43 
    vTcl:DefineAlias "$top.cpd102" "l43" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd103 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 42 
    vTcl:DefineAlias "$top.cpd103" "l42" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd104 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 41 
    vTcl:DefineAlias "$top.cpd104" "l41" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd105 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 40 
    vTcl:DefineAlias "$top.cpd105" "l40" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd106 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 39 
    vTcl:DefineAlias "$top.cpd106" "l39" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd107 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 38 
    vTcl:DefineAlias "$top.cpd107" "l38" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd108 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 37 
    vTcl:DefineAlias "$top.cpd108" "l37" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd109 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 36 
    vTcl:DefineAlias "$top.cpd109" "l36" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd110 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 35 
    vTcl:DefineAlias "$top.cpd110" "l35" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd111 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 34 
    vTcl:DefineAlias "$top.cpd111" "l34" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd112 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 33 
    vTcl:DefineAlias "$top.cpd112" "l33" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd113 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 32 
    vTcl:DefineAlias "$top.cpd113" "l32" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd114 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 31 
    vTcl:DefineAlias "$top.cpd114" "l31" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd115 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 60 
    vTcl:DefineAlias "$top.cpd115" "l60" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd116 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 59 
    vTcl:DefineAlias "$top.cpd116" "l59" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd117 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 58 
    vTcl:DefineAlias "$top.cpd117" "l58" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd118 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 57 
    vTcl:DefineAlias "$top.cpd118" "l57" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd119 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 56 
    vTcl:DefineAlias "$top.cpd119" "l56" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd120 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 55 
    vTcl:DefineAlias "$top.cpd120" "l55" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd121 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 54 
    vTcl:DefineAlias "$top.cpd121" "l54" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd122 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 53 
    vTcl:DefineAlias "$top.cpd122" "l53" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd123 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 52 
    vTcl:DefineAlias "$top.cpd123" "l52" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd124 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 51 
    vTcl:DefineAlias "$top.cpd124" "l51" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd125 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#001154} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 02 
    vTcl:DefineAlias "$top.cpd125" "l2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but126 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Start Calibration} 
    vTcl:DefineAlias "$top.but126" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but128 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {End Calibration} 
    vTcl:DefineAlias "$top.but128" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $top.cpd129 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command destroy_window \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Exit 
    vTcl:DefineAlias "$top.cpd129" "Button3" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab53 \
        -in $top -x 70 -y 170 -anchor nw -bordermode ignore 
    place $top.cpd55 \
        -in $top -x 20 -y 170 -anchor nw -bordermode inside 
    place $top.cpd56 \
        -in $top -x 20 -y 120 -anchor nw -bordermode inside 
    place $top.cpd57 \
        -in $top -x 70 -y 120 -anchor nw -bordermode inside 
    place $top.cpd58 \
        -in $top -x 70 -y 70 -anchor nw -bordermode inside 
    place $top.cpd59 \
        -in $top -x 70 -y 20 -anchor nw -bordermode inside 
    place $top.cpd60 \
        -in $top -x 20 -y 270 -anchor nw -bordermode inside 
    place $top.cpd61 \
        -in $top -x 20 -y 220 -anchor nw -bordermode inside 
    place $top.cpd62 \
        -in $top -x 20 -y 20 -width 24 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.cpd75 \
        -in $top -x 70 -y 220 -anchor nw -bordermode inside 
    place $top.cpd76 \
        -in $top -x 70 -y 270 -anchor nw -bordermode inside 
    place $top.cpd77 \
        -in $top -x 170 -y 70 -anchor nw -bordermode inside 
    place $top.cpd78 \
        -in $top -x 170 -y 20 -anchor nw -bordermode inside 
    place $top.cpd79 \
        -in $top -x 120 -y 270 -anchor nw -bordermode inside 
    place $top.cpd80 \
        -in $top -x 120 -y 220 -anchor nw -bordermode inside 
    place $top.cpd81 \
        -in $top -x 120 -y 170 -anchor nw -bordermode inside 
    place $top.cpd82 \
        -in $top -x 120 -y 120 -anchor nw -bordermode inside 
    place $top.cpd83 \
        -in $top -x 120 -y 70 -anchor nw -bordermode inside 
    place $top.cpd84 \
        -in $top -x 120 -y 20 -anchor nw -bordermode inside 
    place $top.cpd85 \
        -in $top -x 220 -y 270 -anchor nw -bordermode inside 
    place $top.cpd86 \
        -in $top -x 220 -y 220 -anchor nw -bordermode inside 
    place $top.cpd87 \
        -in $top -x 220 -y 170 -anchor nw -bordermode inside 
    place $top.cpd88 \
        -in $top -x 220 -y 120 -anchor nw -bordermode inside 
    place $top.cpd89 \
        -in $top -x 220 -y 70 -anchor nw -bordermode inside 
    place $top.cpd90 \
        -in $top -x 220 -y 20 -anchor nw -bordermode inside 
    place $top.cpd91 \
        -in $top -x 170 -y 270 -anchor nw -bordermode inside 
    place $top.cpd92 \
        -in $top -x 170 -y 220 -anchor nw -bordermode inside 
    place $top.cpd93 \
        -in $top -x 170 -y 170 -anchor nw -bordermode inside 
    place $top.cpd94 \
        -in $top -x 170 -y 120 -anchor nw -bordermode inside 
    place $top.cpd95 \
        -in $top -x 420 -y 70 -anchor nw -bordermode inside 
    place $top.cpd96 \
        -in $top -x 420 -y 20 -anchor nw -bordermode inside 
    place $top.cpd97 \
        -in $top -x 370 -y 270 -anchor nw -bordermode inside 
    place $top.cpd98 \
        -in $top -x 370 -y 220 -anchor nw -bordermode inside 
    place $top.cpd99 \
        -in $top -x 370 -y 170 -anchor nw -bordermode inside 
    place $top.cpd100 \
        -in $top -x 370 -y 120 -anchor nw -bordermode inside 
    place $top.cpd101 \
        -in $top -x 370 -y 70 -anchor nw -bordermode inside 
    place $top.cpd102 \
        -in $top -x 370 -y 20 -anchor nw -bordermode inside 
    place $top.cpd103 \
        -in $top -x 320 -y 270 -anchor nw -bordermode inside 
    place $top.cpd104 \
        -in $top -x 320 -y 220 -anchor nw -bordermode inside 
    place $top.cpd105 \
        -in $top -x 320 -y 170 -anchor nw -bordermode inside 
    place $top.cpd106 \
        -in $top -x 320 -y 120 -anchor nw -bordermode inside 
    place $top.cpd107 \
        -in $top -x 320 -y 70 -anchor nw -bordermode inside 
    place $top.cpd108 \
        -in $top -x 320 -y 20 -anchor nw -bordermode inside 
    place $top.cpd109 \
        -in $top -x 270 -y 270 -anchor nw -bordermode inside 
    place $top.cpd110 \
        -in $top -x 270 -y 220 -anchor nw -bordermode inside 
    place $top.cpd111 \
        -in $top -x 270 -y 170 -anchor nw -bordermode inside 
    place $top.cpd112 \
        -in $top -x 270 -y 120 -anchor nw -bordermode inside 
    place $top.cpd113 \
        -in $top -x 270 -y 70 -anchor nw -bordermode inside 
    place $top.cpd114 \
        -in $top -x 270 -y 20 -anchor nw -bordermode inside 
    place $top.cpd115 \
        -in $top -x 470 -y 270 -anchor nw -bordermode inside 
    place $top.cpd116 \
        -in $top -x 470 -y 220 -anchor nw -bordermode inside 
    place $top.cpd117 \
        -in $top -x 470 -y 170 -anchor nw -bordermode inside 
    place $top.cpd118 \
        -in $top -x 470 -y 120 -anchor nw -bordermode inside 
    place $top.cpd119 \
        -in $top -x 470 -y 70 -anchor nw -bordermode inside 
    place $top.cpd120 \
        -in $top -x 470 -y 20 -anchor nw -bordermode inside 
    place $top.cpd121 \
        -in $top -x 420 -y 270 -anchor nw -bordermode inside 
    place $top.cpd122 \
        -in $top -x 420 -y 220 -anchor nw -bordermode inside 
    place $top.cpd123 \
        -in $top -x 420 -y 170 -anchor nw -bordermode inside 
    place $top.cpd124 \
        -in $top -x 420 -y 120 -anchor nw -bordermode inside 
    place $top.cpd125 \
        -in $top -x 20 -y 70 -anchor nw -bordermode inside 
    place $top.but126 \
        -in $top -x 20 -y 310 -width 117 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.but128 \
        -in $top -x 150 -y 310 -width 117 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.cpd129 \
        -in $top -x 419 -y 310 -width 77 -height 34 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top47

