#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.3.1
# In conjunction with Tcl version 8.6
#    Oct 24, 2014 08:01:45 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import RebootSys_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('System Reboot')
    root.geometry('249x58+381+162')
    w = System_Reboot (root)
    RebootSys_support.init(root, w)
    root.mainloop()

w = None
def create_System_Reboot (root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('System Reboot')
    w.geometry('249x58+381+162')
    w.resizable(width=FALSE, height=FALSE)
    w_win = System_Reboot (w)
    RebootSys_support.init(w, w_win, param)
    root.after(30000,destroy_System_Reboot)
    w.protocol("WM_DELETE_WINDOW", doNothing)
    return w_win

def destroy_System_Reboot ():
    global w
    w.destroy()
    w = None

def doNothing ():
    return


class System_Reboot:
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])
        master.configure(background="#d9d9d9")
        master.configure(highlightbackground="#d9d9d9")
        master.configure(highlightcolor="black")


        self.TProgressbar1 = ttk.Progressbar (master)
        self.TProgressbar1.place(relx=0.04,rely=0.47,relheight=0.38
                ,relwidth=0.92)
        self.TProgressbar1.configure(length="20")
        self.TProgressbar1.configure(mode="indeterminate")
        self.TProgressbar1.start(100)

        self.Label1 = Label (master)
        self.Label1.place(relx=0.02,rely=0.1,height=21,width=112)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor=W)
        self.Label1.configure(background=_bgcolor)
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Rebooting System:''')





if __name__ == '__main__':
    vp_start_gui()



