#############################################################################
# Generated by PAGE version 4.3.1
# in conjunction with Tcl version 8.6
#    Oct 24, 2014 10:38:26 PM




#############################################################################
## vTcl Code to Load Stock Images


if {![info exist vTcl(sourcing)]} {
#############################################################################
## Procedure:  vTcl:rename

proc ::vTcl:rename {name} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.

    regsub -all "\\." $name "_" ret
    regsub -all "\\-" $ret "_" ret
    regsub -all " " $ret "_" ret
    regsub -all "/" $ret "__" ret
    regsub -all "::" $ret "__" ret

    return [string tolower $ret]
}

#############################################################################
## Procedure:  vTcl:image:create_new_image

proc ::vTcl:image:create_new_image {filename {description {no description}} {type {}} {data {}}} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.
    # Does the image already exist?
    if {[info exists ::vTcl(images,files)]} {
        if {[lsearch -exact $::vTcl(images,files) $filename] > -1} { return }
    }
    if {![info exists ::vTcl(sourcing)] && [string length $data] > 0} {
        set object [image create  [vTcl:image:get_creation_type $filename]  -data $data]
    } else {
        # Wait a minute... Does the file actually exist?
        if {! [file exists $filename] } {
            # Try current directory
            set script [file dirname [info script]]
            set filename [file join $script [file tail $filename] ]
        }

        if {![file exists $filename]} {
            set description "file not found!"
            ## will add 'broken image' again when img is fixed, for
            ## now create empty
            set object [image create photo -width 1 -height 1]
        } else {
            set object [image create  [vTcl:image:get_creation_type $filename]  -file $filename]
        }
    }

    set reference [vTcl:rename $filename]
    set ::vTcl(images,$reference,image)       $object
    set ::vTcl(images,$reference,description) $description
    set ::vTcl(images,$reference,type)        $type
    set ::vTcl(images,filename,$object)       $filename

    lappend ::vTcl(images,files) $filename
    lappend ::vTcl(images,$type) $object
    set ::vTcl(imagefile,$object) $filename   ;# Rozen
    # return image name in case caller might want it
    return $object
}

#############################################################################
## Procedure:  vTcl:image:get_image

proc ::vTcl:image:get_image {filename} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.

    set reference [vTcl:rename $filename]

    # Let's do some checking first
    if {![info exists ::vTcl(images,$reference,image)]} {
        # Well, the path may be wrong; in that case check
        # only the filename instead, without the path.

        set imageTail [file tail $filename]

        foreach oneFile $::vTcl(images,files) {
            if {[file tail $oneFile] == $imageTail} {
                set reference [vTcl:rename $oneFile]
                break
            }
        }
    }
    # Rozen. There follows a hack in case one wants to rerun a tcl
    # file which contains a file name where an image is expected.
    if {![info exists ::vTcl(images,$reference,image)]} {
        set ::vTcl(images,$reference,image)  [vTcl:image:create_new_image $filename]
    }
    return $::vTcl(images,$reference,image)
}

#############################################################################
## Procedure:  vTcl:image:get_creation_type

proc ::vTcl:image:get_creation_type {filename} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.

    switch [string tolower [file extension $filename]] {
        .ppm -
        .jpg -
        .bmp -
        .gif    {return photo}
        .xbm    {return bitmap}
        default {return photo}
    }
}

foreach img {


            } {
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

}
#############################################################################
## vTcl Code to Load User Images

catch {package require Img}

foreach img {

        {{$[pwd]/camera.png} {user image} user {}}
        {{$[pwd]/sett.png} {user image} user {}}
        {{$[pwd]/calib.png} {user image} user {}}
        {{$[pwd]/exit.png} {user image} user {}}

            } {
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set set,origin 0
        set set,size 0
        set runvisible 1
    }
    set site_3_0 $base.m37
    set site_3_0 $base.m37
    namespace eval ::widgets_bindings {
        set tagslist {_TopLevel TButton9}
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 200x200+156+156; update
    wm maxsize $top 1276 773
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page"
    bindtags $top "$top Page all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -menu "$top.m37" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm withdraw $top
    wm focusmodel $top passive
    wm maxsize $top 308 312
    wm minsize $top 308 312
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm title $top "Matrix Ring Control"
    vTcl:DefineAlias "$top" "Matrix Ring Control" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "Toplevel all _TopLevel"
    menu $top.m37 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $top.m37 add cascade \
        -menu "$top.m37.men38" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label File 
    set site_3_0 $top.m37
    menu $site_3_0.men38 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men38 add command \
        -activebackground {#ffffff} -background {#d9d9d9} \
        -command destroy_window \
        -font [vTcl:font:getFontFromDescr "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Exit 
    $top.m37 add cascade \
        -menu "$top.m37.men41" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label Tools 
    set site_3_0 $top.m37
    menu $site_3_0.men41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men41 add command \
        -activebackground {#ffffff} -activeforeground {#000000} \
        -background {#d9d9d9} -command usbReset -font TkMenuFont \
        -foreground {#000000} -label {USB Reset} 
    $site_3_0.men41 add command \
        -activebackground {#ffffff} -activeforeground {#000000} \
        -background {#d9d9d9} -command sysReboot -font TkMenuFont \
        -foreground {#000000} -label {System Reboot} 
    message $top.mes65 \
        -anchor w -background {#d8d8d8} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -relief sunken \
        -text Message -textvariable Msg -width 290 
    vTcl:DefineAlias "$top.mes65" "Message2" vTcl:WidgetProc "Matrix Ring Control" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu67 \
        -command destroy_window -takefocus {} -text Exit \
        -image [vTcl:image:get_image [file join C:/ page {Matrix GUI} exit.png]] \
        -cursor hand2 
    vTcl:DefineAlias "$top.tBu67" "Exit" vTcl:WidgetProc "Matrix Ring Control" 1
    bind $top.tBu67 <Enter> {
        InExit
    }
    bind $top.tBu67 <Leave> {
        Out
    }
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu66 \
        -takefocus {} -text Clibrate \
        -image [vTcl:image:get_image [file join C:/ page {Matrix GUI} calib.png]] \
        -cursor hand2 
    vTcl:DefineAlias "$top.tBu66" "Arrows" vTcl:WidgetProc "Matrix Ring Control" 1
    bind $top.tBu66 <Enter> {
        InCal
    }
    bind $top.tBu66 <Leave> {
        Out
    }
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu56 \
        -command Captured -takefocus {} -text Capture \
        -image [vTcl:image:get_image [file join C:/ page {Matrix GUI} camera.png]] \
        -cursor hand2 
    vTcl:DefineAlias "$top.tBu56" "Camera" vTcl:WidgetProc "Matrix Ring Control" 1
    bind $top.tBu56 <Enter> {
        InCam
    }
    bind $top.tBu56 <Leave> {
        Out
    }
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu78 \
        -takefocus {} -text Configuraition \
        -image [vTcl:image:get_image [file join C:/ page {Matrix GUI} sett.png]] 
    vTcl:DefineAlias "$top.tBu78" "Configuraition" vTcl:WidgetProc "Matrix Ring Control" 1
    bind $top.tBu78 <Enter> {
        InSet
    }
    bind $top.tBu78 <Leave> {
        Out
    }
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.mes65 \
        -in $top -x 11 -y 270 -width 289 -height 30 -anchor nw \
        -bordermode ignore 
    place $top.tBu67 \
        -in $top -x 240 -y 200 -width 60 -height 60 -anchor nw \
        -bordermode ignore 
    place $top.tBu66 \
        -in $top -x 80 -y 200 -width 60 -height 60 -anchor nw \
        -bordermode ignore 
    place $top.tBu56 \
        -in $top -x 10 -y 10 -width 290 -height 180 -anchor nw \
        -bordermode ignore 
    place $top.tBu78 \
        -in $top -x 10 -y 200 -width 60 -height 60 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}
#############################################################################
## Binding tag:  TButton9

bind "TButton9" <Enter> {
    InSet
}
bind "TButton9" <Leave> {
    Out
}

Window show .
Window show .top36

