#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.3.1
# In conjunction with Tcl version 8.6
#    Oct 24, 2014 07:29:18 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import resetUSB_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('USB_Reset')
    root.geometry('249x58+381+162')
    w = USB_Reset (root)
    resetUSB_support.init(root, w)
    root.mainloop()

w = None
def create_USB_Reset (root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('USB Reset')
    w.geometry('249x58+381+162')
    w.resizable(width=FALSE, height=FALSE)
    w_win = USB_Reset (w)
    resetUSB_support.init(w, w_win, param)
    root.after(500,destroy_USB_Reset)
    return w_win

def destroy_USB_Reset ():
    global w
    w.destroy()
    w = None


class USB_Reset:
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])
        master.configure(background="#d9d9d9")


        self.TProgressbar1 = ttk.Progressbar (master)
        self.TProgressbar1.place(relx=0.04,rely=0.47,relheight=0.38
                ,relwidth=0.92)
        self.TProgressbar1.configure(length="20")
        self.TProgressbar1.configure(mode="indeterminate")
        self.TProgressbar1.configure(maximum="15")
        self.TProgressbar1.start(1)

        self.Label1 = Label (master)
        self.Label1.place(relx=0.02,rely=0.1,height=21,width=82)
        self.Label1.configure(anchor=W)
        self.Label1.configure(background=_bgcolor)
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Resetting USB:''')
        self.Label1.configure(width=82)





if __name__ == '__main__':
    vp_start_gui()



